spring.config.import=optional:file:.env[.properties]

spring.application.name=telestore
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.auto-index-creation=true

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}