spring.config.import=optional:file:.env[.properties]

spring.application.name=telestore
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.auto-index-creation=true

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}

jwt.jwt-secert=${JWT_SECRET}
jwt.jwt-expiration=${JWT_EXPIRATION}

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

oauth2.redirect-uri=${REDIRECT_URI}

# Allow individual files up to xxMB
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}

# Allow total request size up to xxMB
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

frontend.host-url=${FRONTEND_HOST_URL}

# Cookies Settings
app.security.cookie.secure=${COOKIE_SECURE}
app.security.cookie.same-site=${COOKIE_SAME_SITE}

# Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Gmail SMTP alternative for production
resend.api-key=${RESEND_API_KEY}
resend.from=onboarding@resend.dev

brevo.api-key=${BREVO_API_KEY}
brevo.from=devargha2023@gmail.com

email.provider=${EMAIL_PROVIDER:brevo}

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logs the actual BSON commands/queries sent to MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Logs connection pooling, cluster status, and server discoveries
logging.level.org.mongodb.driver=WARN
