spring.config.import=optional:file:.env[.properties]

spring.application.name=telestore
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.auto-index-creation=true

telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}

jwt.jwt-secert=${JWT_SECRET}
jwt.jwt-expiration=${JWT_EXPIRATION}

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

oauth2.redirect-uri=${REDIRECT_URI}

# Allow individual files up to xxMB
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}

# Allow total request size up to xxMB
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

frontend.host-url=${FRONTEND_HOST_URL}